services:
  backend:
    build: backend
    # depends_on:
    #   - mongodb
    restart: unless-stopped
    extra_hosts:
        - "host.docker.internal:host-gateway"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

#   mongodb:
#     image: mongo
#     hostname: mongodb
#     ports:
#       - 27017:27017
#     volumes:
#       - db_volume:/data/db:rw
#       - db_conf:/data/configdb
#     restart: always
#     logging:
#       driver: "json-file"
#       options:
#         max-size: "10m"
#         max-file: "3"

# volumes:
#   db_volume:
#   db_conf:
