services:
  backend:
    build: backend
    restart: unless-stopped
    environment:
      - MONGO_URL=mongodb://host.docker.internal:27017
    extra_hosts:
        - "host.docker.internal:host-gateway"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
